### ISSUE TITLE
ssh-add stuck

### ISSUE THREAD

**Issue by dungdm93** [tianon/docker-bash#7] opened 2017-09-07 03:35 UTC
I use `bash:4.4` to build OpenSSH client image. `Dockerfile` is bellow:
```Dockerfile
FROM bash:4.4

RUN set -eux; \
    # openssh = openssh-client + openssh-server + openssh-sftp-server
    apk add -U --no-cache openssh; \
    rm -rf /var/cache/apk/*

COPY ssh /root/.ssh
```
However, whenever I run it, it always stuck at `ssh-add` commad.
```bash
$ eval $(ssh-agent -s)
$ ssh-add <( cat  /path/to/SSH_PRIVATE_KEY ) # <== stuck here
```

**Comment by tianon** [comment] 2017-09-22 23:01
This is a duplicate of https://github.com/tianon/docker-bash/issues/4 -- in your case, I'd recommend just passing the file directly to `ssh-add` instead. :+1:

**Closed as completed by tianon** 2017-09-22 23:01 UTC

**Comment by dungdm93** [comment] 2017-10-28 07:27
@tianon 
If I want to `ssh-add` from environment variable, How can I do that?

**Comment by tianon** [comment] 2017-10-30 18:59
@dungdm93 you could simply use pipes rather than process substitution:
```console
$ echo $ABC_ENV | ssh-add
```
(not sure if `ssh-add` will read from stdin by default -- if not, try using `-` or `/dev/stdin` as the filename)

**Comment by dungdm93** [comment] 2017-11-03 07:47
Thank you @tianon :+1: 

It works with:
```bash
$ echo $FOOBAR | ssh-add -
--or--
$ echo $FOOBAR | ssh-add /dev/stdin
```
